Output usage.gif
Set FontSize 13
Set Width 1024
Set Height 480
Set Padding 10
Sleep 1ms
Escape
Type "[200~target/x86_64-unknown-linux-musl/release/pytorch-trace-tui"
Escape
Type "[201~"
Enter
Sleep 500ms
Type "1"
Enter
Sleep 1s
Escape
Type "[<35;38;4M"
Escape
Type "[<35;36;4M"
Escape
Type "[<35;34;4M"
Escape
Type "[<35;33;4M"
Escape
Type "[<35;32;4M"
Escape
Type "[<0;32;4M"
Escape
Type "[<0;32;4mwwwwwwwwwww"
Sleep 500ms
Type "/"
Sleep 500ms
Type "moe"
Sleep 2s
Type "_"
Sleep 2s
Type "gemm"
Sleep 2s
Escape
Type "wwwwwwwww"
Sleep 1s
Type "a"
Sleep 1s
Type "a"
Sleep 1s
Type "d"
Sleep 1s
Type "d"
Sleep 1s
Type "d"
Sleep 1s
Type "a"
Sleep 2s
Type "n"
Sleep 3s
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Sleep 1s
Type "y"
Sleep 1s
Type "q"
Sleep 500ms
Type "head"
Sleep 500ms
Type " -5 "
Sleep 500ms
Type "ker"
Tab
Sleep 500ms
Enter
Sleep 2.5s

